server{
    listen 80;

    #前端静态文件
    location / {
        root / user/share/nginx/html;
        index index.html;
    }

    #API反向代理（转发给后端容器）
    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
    }
}