services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: agentforge
    ports:
    - "5432:5432"

    healthcheck:  #这是工程规范，确保数据库完全就绪了再启动后端
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    #使用./backend文件来构建镜像
    ports:
      - "8000:8000"
    #把容器内部的端口映射到宿主机
    env_file:
      - .env
    environment:
      - HTTP_PROXY=http://host.docker.internal:33210
      - HTTPS_PROXY=http://host.docker.internal:33210
      - NO_PROXY=postgres,redis,api.deepseek.com,localhost,127.0.0.1
    volumes:
      - ./backend/app:/app/app  #挂载本地代码，改完就生效（不用rebuild）
      #挂载之后，本地修改代码保存之后直接通过“管道”同步进容器内部，加上--reload参数，Uvicorn检测到文件夹变了，瞬间自动重启服务，刷新浏览器就能看到效果
      #挂载的价值--实现“本地写代码，容器里热更新”
    depends_on:
      postgres:
        condition: service_healthy  #等数据库健康了再启动
      redis:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html

volumes:
  pg_data:
  redis_data: